# Generated by Django 6.1 on 2026-09-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('compliance_score', models.FloatField(default=0)),
                ('violations_count', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
