# Generated by Django 6.1 on 2026-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_success', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(blank=True, max_length=500, null=True)),
                ('net_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('consumer_care', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Analysis Pending', max_length=50)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
