# Generated by Django 6.1 on 2026-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='detected_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='detected_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='ml_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='ml_label',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=100),
        ),
    ]
