# Generated by Django 6.1 on 2026-09-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
